services:
  dev:
    build:
      dockerfile: .dockerfile
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/workspace:${PYTHONPATH}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
