arch_layout: ["m4", ["T22"], "m4"]
d_model: [1024, 1536]
d_intermediate: [0, 4096]
n_chunk_select: [4]
vocab_size: 256
encoder_ssm_cfg:
  chunk_size: 256
  d_conv: 4
  d_state: 128
  expand: 2
decoder_ssm_cfg:
  chunk_size: 256
  d_conv: 4
  d_state: 128
  expand: 2
encoder_attn_cfg:
  num_heads: [16, 16]
  rotary_emb_dim: [32, 48]
  window_size: [100, -1]
decoder_attn_cfg:
  num_heads: [16, 16]
  rotary_emb_dim: [32, 48]
  window_size: [10, 10]
tie_embeddings: false
